### ISSUE TITLE
建议添加.gitignore 文件

### ISSUE THREAD

**Issue by wangzilong1997** [pubdreamcc/Node.js#1]

**Comment by pubdreamcc** [comment]
感谢提供的建议，后面demo案例会添加忽略文件配置

**Comment by pubdreamcc** [comment]
> _No description provided._

感谢提供的建议，后面demo案例会添加忽略文件配置

**Comment by wangzilong1997** [comment]
> > _No description provided._
> 
> 感谢提供的建议，后面demo案例会添加忽略文件配置

感谢提供的参考代码

**Comment by pubdreamcc** [comment]
> 的参考代

如果你觉得对你有帮助的话，欢迎转发给其他的伙伴吧~
